apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-kubernetes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: prometheus-kubernetes
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: prometheus-operator
    version: 6.11.0
  values:
    alertmanager:
      enabled: true
      ingress:
        enabled: true
        hosts:
        - alertmanager.iflan.local
      service: 
        type: NodePort
      config:
        global:
          resolve_timeout: 5m
        route:
          group_interval: 5m
          group_wait: 30s
          repeat_interval: 12h
          group_by: 
            - job
            - alertname
            - pod_name
            - namespace
          receiver: "null"
          routes:
          - match:
              alertname: Watchdog
            receiver: "null"
        receivers:
        - name: "null"
    grafana:
      enabled: true
      ingress:
        enabled: true
        hosts:
        - grafana.iflan.local
      service: 
        type: NodePort
      adminPassword: iflan@123
    kubeApiServer:
      enabled: true
    kubeControllerManager:
      enabled: true
    kubeDns:
      enabled: true
    kubeEtcd:
      enabled: true
    kubeScheduler:
      enabled: true
    kubeStateMetrics:
      enabled: true
    kubelet:
      enabled: true
    nodeExporter:
      enabled: true
    prometheus:
      enabled: true
      ingress:
        enabled: true
        hosts:
        - prometheus.iflan.local
      service: 
        type: NodePort
    prometheus-node-exporter:
      extraArgs:
      - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
      - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
    prometheusOperator:
      enabled: true
      createCustomResource: false
